### ISSUE TITLE
New Contributor 

### ISSUE THREAD

**Issue by theclub654** [JayFoxRox/futurama-tools#2]
I would love to contribute to this project are you still working on it

**Comment by JayFoxRox** [comment]
I'm not actively working on it. In general, I've recently decided to stop most of my involvement with FOSS.

However, I consider most of these tools complete. Most of the formats are understood and most things can be analyzed.

The only big missing feature is probably a FUL (macro-)assembler and potentially a decompiler. That would be insanely helpful for testing some of the more interesting, undocumented and unused opcodes (like `FsSetKnarkEffect`). I'm also aware of some potentially unfinished (?) animations / easter-eggs. If we had an assembler we could trigger those.
Having an assembler would also help with being able to mod the game, although that is hindered by lack of tooling in [NifTools](https://github.com/JayFoxRox/futurama-tools#media-nif) (which is beyond my control and out of scope).

If you see anything that should be fixed, create an issue or send a PR.
I won't be adding a new contributor probably (certainly not someone I don't already know), as I'd still like to review changes.

Closed.

---

*I've created #3 which I still had stored locally. I also have some other (less important) documents about Futurama that I only kept locally, but I'm not sure yet wether I'll make them public.*
